version: "3.9"
services:
  dhelp:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dhelp-build-stage
    ports:
      - 4000:4000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/dhelp"]